spring:
  profiles:
    group:
      local: chatbot-common, db-local
      development: chatbot-common, db-local
      production: chatbot-common

---
spring:
  jackson:
    default-property-inclusion: NON_NULL

---
spring.config.activate.on-profile: chatbot-common
chatbot:
  config:
    image_link:
      thumbnail: https://play.google.com/store/apps/details?id=com.schoolinfo.keris&hl=ko

---
spring.config.activate.on-profile: db-local
spring:
  data:
    mongodb:
      uri: mongodb+srv://alimtoyou:${MONGODB_PASSWORD}@alimtoyou.nqonrsi.mongodb.net/alimtoyou_dev
